name: gamma
channels:
  - conda-forge
  - anaconda
  - pytorch
  - numba
dependencies:
  - python=3.7   
  - pip
  - pytorch-cpu
  - scikit-learn
  - scikit-image
  - cvxpy
  - h5py
  - tqdm
  - cudatoolkit=10.2
  - pip:
    - -r requirements.txt